import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Meu Boyler Plate",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
      <div>
        <p>OPA</p>
        {children}
        <p>Mais Produtos</p>
      </div>
  );
}
